### ISSUE TITLE
add support for DNS01 domain delegation

### ISSUE THREAD

**Issue by gregjhogan** [terrycain/certbot-dns-azure#14]
This allows the domain used for validation to be completely different than the domain name you are requesting a certificate for.

Here is the best example of how this works I can find:
https://cert-manager.io/docs/configuration/acme/dns01/#delegated-domains-for-dns01

**Comment by mdhowle** [comment]
I submitted a pull request #17 that works around this issue by supplying the full resource ID. This should work for your use case. Let me know if you are able to test this.

**Comment by terrycain** [comment]
PR #18 was merged
