### ISSUE TITLE
Feature request: add support to clear the TXT record but not remove it

### ISSUE THREAD

**Issue by theodiem** [terrycain/certbot-dns-azure#20]
Azure allows a principal to manage individual records of a zone. This allows to have different credentials per record.

It would be nice to clear the TXT record (setting it to blank ot '-') instead of deleting the record, so the role assignment is persisted.

IMHO, security-wise, not sure how much advantage leaving a blank record instead of deleting it, as you can query https://crt.sh/ (certificate transparency logs) for a given domain, so knowing that exists an _acme-challenge entry in a domain isn't any different at all from querying crt.sh.

Still, when combined with #14 is very useful to have a single zone to hold challenges across several domains without having multiple zones registered in Azure DNS (saving on billing, since it charges per zone + per million queries).

**Comment by terrycain** [comment]
This makes sense, feel free to PR to add a config option to make this so.

**Comment by terrycain** [comment]
This is out on 2.2.0b0 or the snap edge channel
