### ISSUE TITLE
Remove certbot<2 constraint

### ISSUE THREAD

**Issue by alexzorin** [terrycain/certbot-dns-azure#28]
https://github.com/terrycain/certbot-dns-azure/commit/c696da3f51ee0eb8527c282c8972f5f56454fc43 added a `certbot>=1.18.0,<2.0` constraint to the plugin.

We recently pushed the Certbot snap out to every snap user, so the plugin is broken there due to a constraint conflict.

This was reported at https://community.letsencrypt.org/t/certbot-versionconflict-after-update-on-ubuntu/193141/5.

Would it be possible to remove the constraint and republish the snap? The plugin should otherwise work just fine with Certbot 2.x. Thank you.

**Comment by dduportal** [comment]
The Jenkins infrasturcture team is also having the same issue: https://github.com/jenkins-infra/helpdesk/issues/3399 .

Is there any way to help on that topic?

**Comment by dduportal** [comment]
Hello @terrycain , is there any way we can help?

**Comment by terrycain** [comment]
Sorry, been away for a bit. looking at this today.

**Comment by terrycain** [comment]
Fixed, snap 2.1.0 has bee released, and promoted to the stable channel
