### ISSUE TITLE
Subdomain handling is dependent on azure.ini order.

### ISSUE THREAD

**Issue by snigel** [terrycain/certbot-dns-azure#30]
certbot version 2.3.0
certbot-dns-azure version 1.5.0

While trying to update certs I noticed something peculiar.
`certbot renew --cert-name test.domain.com`
This tried to create the _acme_challenge TXT post in domain.com, not test.domain.com which I expected.

So I took a look at azure.ini
> dns_azure_zone4 = domain.io:/subscriptions/<subscription-id>/resourceGroups/group-dns?
> dns_azure_zone5 = prod.domain.io:/subscriptions/<subscription-id>/resourceGroups/group-dns
> dns_azure_zone6 = test.domain.io:/subscriptions/<subscription-id>/resourceGroups/group-dns

Could it be that the top domain incorrectly got selected? I switched the order to have the top domain last.
>dns_azure_zone4 = prod.domain.io:/subscriptions/<subscription-id>/resourceGroups/group-dns
>dns_azure_zone5 = test.domain.io:/subscriptions/<subscription-id>/resourceGroups/group-dns
>dns_azure_zone6 = domain.io:/subscriptions/<subscription-id>/resourceGroups/group-dns?

Now the renew command works fine, the _acme post ends up in the DNS for test.domain.io instead, so azure.ini seems to be order dependant. 

I read through the documentation here:
https://certbot-dns-azure.readthedocs.io/en/latest/
But I could find that the azure.ini file is supposed to be order dependent and there were no examples reflecting my use case with both subdomains and the top domain.

I took a look at certbot-dns-azure code, added comments of how I understand the flow.

```
def _get_ids_for_domain(self, domain: str):
        # domain_zoneid.items format
        # key: domain.io 
        # value: /subscriptions/<subscription-id>/resourceGroups/group-dns

        # I'm assuming the domain argument is what I'm supplying on commandline
        # ie test.domain.io

        try:
            for azure_dns_domain, resource_group in self.domain_zoneid.items():
                # If the first item in the list is the top domain
                # azure_dns_domain = domain.io
                # resource_group = /subscriptions/<subscription-id>/resourceGroups/group-dns 

                # Look to see if domain ends with key, to cover subdomains
                if domain.endswith(azure_dns_domain):
                    # if "test.domain.io" ends with "domain.io"
                    # Ok, my sub domain ends with the first item in the list which is the top domain.

                    subscription_id = resource_group.split('/')[2]
                    # subscription_id = <subscription-id>
                    rg_name = resource_group.split('/')[4]
                    # rg_name = group_dns
                    return azure_dns_domain, subscription_id, rg_name
                    # return domain.io, <subscription-id>, group_dns
```

It seems this function will return the top domain, rather than the subdomain, if the top domain comes first in the list.
The _perform function seems to use the return azure_dns_domain, while printing error messages using the domain.

**Comment by terrycain** [comment]
Yep, reading through the code, you are correct, this is a bug. In theory, sorting the domains from self.domain_zoneid.items() by length then iterating over them would prevent this, and mean the zone order in the ini config should then be position independent. 

Bit busy this weekend/week but I'll look at fixing it next weekend (11th ish). Good spot though!

**Comment by terrycain** [comment]
I have a fix for this, not committed yet but will be out soon

**Comment by snigel** [comment]
That's great to hear. I'm thankful you're working on it.

**Comment by terrycain** [comment]
This is out on 2.2.0b0 or the snap edge channel
