### ISSUE TITLE
Some DNS records not being added to Azure

### ISSUE THREAD

**Issue by charlesomer** [terrycain/certbot-dns-azure#35]
Hi, thanks for your work on this, I've been able to certify multiple subdomains successfully in different dns regions. However, I've noticed an odd bug (?) where some domains won't get a DNS record at all in Azure unless they are placed at the start of the list of certbot domains. I.e. `-d flakey-subdomain-1 -d flakey-subdomain-2`.

So far I've not been able to identify why this might be and I'm concerned that it may fail in the future. Is there anything I can try to figure out what would cause this?

The list of domains are in the following format:
`*.[different].subdomain.domain.com`

Thank you
Charles

**Comment by terrycain** [comment]
How are you installing certbot, is it via snap or pip install? What version?

Realistically I'll either need logs or a way to troubleshoot this. Its possible its related to this - https://github.com/terrycain/certbot-dns-azure/issues/30 There is a prerelease version `2.2.0b0` / its in the snap edge channel, which might help.

**Comment by charlesomer** [comment]
Installed via pip install and I was using version `2.1.0`.

I've now tried `2.2.0b0` though and this seems to have fixed the issue! Fantastic

I'll close this and see how it goes using the prerelease version

**Comment by terrycain** [comment]
Cool, let me know in a week or so if it solves any issues and i'll promote that version to v2.2.0 official
