### ISSUE TITLE
Dependency on azure-core>=1.25.0

### ISSUE THREAD

**Issue by osirisinferi** [terrycain/certbot-dns-azure#40]
In https://github.com/terrycain/certbot-dns-azure/commit/0b158bb4430f60ec724e726484f5f2fd6ab84486 the usage of `azure.core.utils.CaseInsensitiveDict` was added.

However, this implementation wasn't added until [`azure-core-1.25.0`](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CHANGELOG.md#1250-2022-08-04).

Currently, `certbot-dns-azure` only depends on `azure-identity>=1.11.0` and `azure-mgmt-dns>=8.0.0`. Currently, `azure-mgmnt-dns` doesn't depend on `azure-core` entirely and `azure-identity` depends on `azure-core<2.0.0,>=1.11.0`, so that's not enough either.

Perhaps it's wise to add a dependency on `azure-core>=1.25.0`?

**Comment by terrycain** [comment]
Oh, yeah definitely, great spot!

**Comment by terrycain** [comment]
Released 2.4.0 to PyPI and a snap to the edge channel, will promote the snap to stable in a week.
